Filtros/Models/K19Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Filtros.Models
{
    public class K19Context : DbContext
    {
        public DbSet<Produto> Produtos { get; set; }
    }
}

Filtros/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Filtros.Models
{
    public class Produto
    {
        public int ProdutoID { get; set; }
        public string Nome { get; set; }
        public double Preco { get; set; }

    }
}

Filtros/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Filtros.Models
{
    public class Usuario
    {
        public string Username { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Filtros/Controllers/AutenticadorController.cs
using Filtros.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Filtros.Controllers
{
    public class AutenticadorController : Controller
    {
        //
        // GET: /Autenticador/

        public ActionResult Formulario()
        {
            return View();
        }

        public ActionResult Entrar(Usuario usuario) 
        { 
            if (usuario.Username != null && usuario.Password != null && 
                usuario.Username.Equals("K19") && usuario.Password.Equals("K19"))
            {
                //Session["Usuario"] = usuario;
                FormsAuthentication.SetAuthCookie(usuario.Username, false);
                return RedirectToAction("Index", "Produto");
            }
            else
            {
                ViewBag.Mensagem = "Usuário  ou Senha incorreta!";
                return View("Formulario");
            }
        }

        public ActionResult Sair()
        {
            //Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Formulario");
        }




    }
}

Filtros/Controllers/ProdutoController.cs
using Filtros.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Filtros.Controllers
{
    public class ProdutoController : Controller
    {

        private K19Context db = new K19Context();
        //
        // GET: /Produto/

        public ActionResult Index()
        {
            return View(db.Produtos.ToList());
        }

        [Authorize]
        public ActionResult Cadastrar()
        {
            if (Session["Usuario"] != null)
            {
                return View();
            }
            else
            {
                TempData["Mensagem"] = "Acesso não permitido.";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Cadastrar(Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Produtos.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produto);
        }


    }
}

Filtros/Views/Autenticador/Formulario.cshtml
@model Filtros.Models.Usuario

@{
    ViewBag.Title = "Formulario";
}

<h2>Login</h2>

@using (Html.BeginForm("Entrar", "Autenticador")) 
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Usuario</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Username)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Username)
            @Html.ValidationMessageFor(mode => Model.Username)
        </div>


        <div class="editor-label">
            @Html.EditorFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <p>
            <input type="submit" value="Logar" />
        </p>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Filtros/Views/Produto/Cadastrar.cshtml
@model Filtros.Models.Produto

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Produto</legend>

        <div class="editor-label">
            @Html.LabelFor( model => model.Nome )
        </div>
        <div class="editor-field">
            @Html.EditorFor( model => model.Nome )
            @Html.ValidationMessageFor( model => model.Nome )
        </div>

        <div class="editor-label">
            @Html.LabelFor( model => model.Preco )
        </div>
        <div class="editor-field">
            @Html.EditorFor( model => model.Preco )
            @Html.ValidationMessageFor( model => model.Preco )
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Filtros/Views/Produto/Index.cshtml
@model IEnumerable<Filtros.Models.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (TempData["Mensagem"] != null)
{
    <h3>@TempData["Mensagem"]</h3>
}
<h3></h3>
<p>
    @Html.ActionLink("Cadastrar Produto", "Cadastrar")
</p>
<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
        <th>@Html.DisplayNameFor(model => model.Preco)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
            <td>@Html.DisplayFor(modelItem => item.Preco)</td>
        </tr>
    }

</table>

Filtros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @if (User.Identity.IsAuthenticated)
    {
        @:Olá @User.Identity.Name, @Html.ActionLink("Sair", "Sair", "Autenticador")
    }

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>